version: '3'

services:
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: $AWS_ACCESS_KEY
      MINIO_ROOT_PASSWORD: $AWS_SECRET_KEY
    command: server /data --console-address :9001
    restart: always

  create-bucket:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MC_HOST_minio: http://${AWS_ACCESS_KEY}:${AWS_SECRET_KEY}@minio:9000
    entrypoint:
      - sh
      - -c
      - |
        while ! curl -I http://minio:9000/minio/health/live; do echo 'Wait minio to startup...' && sleep 0.1; done; sleep 5;

        mc mb minio/$AWS_BUCKET
        mc anonymous set public minio/$AWS_BUCKET